version: 2
updates:
  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: daily
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "daily"
