name: Setup Node.js Dependency
on: 
  workflow_call:
    inputs:
      runs-on:
        default: ubuntu-latest
        required: false
        type: string

jobs:
  setup: 
    name: Setup Node.js
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: 9
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: app/pnpm-lock.yaml
      - name: Install Dependency
        run: pnpm install --frozen-lockfile